#!/usr/bin/env node
// Pulls narviai.com's News feed from two free, key-less, production-safe
// sources instead of a generic news aggregator: Hacker News (Algolia's
// public search API) for community discussion, and arXiv's public Atom
// feed for research papers. Both explicitly permit this kind of use at
// this volume — no ToS risk the way NewsAPI's free "Developer" tier has
// (it forbids any non-localhost use, production included). Output is
// written verbatim: no summarizing, no paraphrasing, same discipline as
// PRISM's own News tab.
//
// Run: node scripts/fetch-news.js
// Writes: _data/news.yml

const HN_QUERIES = ['AI agent', 'AI safety', 'LLM', 'multi-agent'];
const HN_MIN_POINTS = 20;
const HN_MAX_ITEMS = 8;

const ARXIV_CATEGORIES = ['cs.AI', 'cs.CL', 'cs.MA'];
const ARXIV_MAX_ITEMS = 6;

const OUT_PATH = new URL('../_data/news.yml', import.meta.url);

function yamlEscape(str) {
  return String(str).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

async function fetchHN() {
  const seen = new Map();
  for (const query of HN_QUERIES) {
    const url = `https://hn.algolia.com/api/v1/search_by_date?tags=story&query=${encodeURIComponent(query)}&hitsPerPage=20&numericFilters=points%3E%3D${HN_MIN_POINTS}`;
    const res = await fetch(url);
    if (!res.ok) {
      console.error(`HN fetch failed for "${query}": ${res.status}`);
      continue;
    }
    const data = await res.json();
    for (const hit of data.hits || []) {
      if (!hit.url || !hit.title) continue;
      if (!seen.has(hit.objectID)) {
        seen.set(hit.objectID, {
          title: hit.title,
          url: hit.url,
          points: hit.points,
          comments: hit.num_comments,
          date: hit.created_at,
          discussion: `https://news.ycombinator.com/item?id=${hit.objectID}`,
        });
      }
    }
  }
  return [...seen.values()]
    .sort((a, b) => b.points - a.points)
    .slice(0, HN_MAX_ITEMS);
}

function parseArxivEntries(xml) {
  const entries = [];
  const blocks = xml.split('<entry>').slice(1);
  for (const block of blocks) {
    const title = (block.match(/<title>([\s\S]*?)<\/title>/) || [])[1];
    const link = (block.match(/<link href="([^"]+)" rel="alternate"/) || [])[1];
    const published = (block.match(/<published>([\s\S]*?)<\/published>/) || [])[1];
    const authorMatches = [...block.matchAll(/<name>([\s\S]*?)<\/name>/g)].map(m => m[1].trim());
    if (title && link) {
      entries.push({
        title: title.replace(/\s+/g, ' ').trim(),
        url: link,
        date: published,
        authors: authorMatches,
      });
    }
  }
  return entries;
}

async function fetchArxiv() {
  const category = ARXIV_CATEGORIES.map(c => `cat:${c}`).join('+OR+');
  const url = `https://export.arxiv.org/api/query?search_query=${category}&sortBy=submittedDate&sortOrder=descending&max_results=${ARXIV_MAX_ITEMS}`;
  const res = await fetch(url, { redirect: 'follow' });
  if (!res.ok) {
    console.error(`arXiv fetch failed: ${res.status}`);
    return [];
  }
  const xml = await res.text();
  return parseArxivEntries(xml);
}

function toYaml(community, research) {
  const lines = [];
  lines.push(`# Generated by scripts/fetch-news.js — do not hand-edit.`);
  lines.push(`generated_at: "${new Date().toISOString()}"`);
  lines.push(`community:`);
  for (const item of community) {
    lines.push(`  - title: "${yamlEscape(item.title)}"`);
    lines.push(`    url: "${yamlEscape(item.url)}"`);
    lines.push(`    discussion: "${yamlEscape(item.discussion)}"`);
    lines.push(`    points: ${item.points}`);
    lines.push(`    comments: ${item.comments}`);
    lines.push(`    date: "${yamlEscape(item.date)}"`);
  }
  lines.push(`research:`);
  for (const item of research) {
    lines.push(`  - title: "${yamlEscape(item.title)}"`);
    lines.push(`    url: "${yamlEscape(item.url)}"`);
    lines.push(`    authors: "${yamlEscape(item.authors.slice(0, 3).join(', ') + (item.authors.length > 3 ? ' et al.' : ''))}"`);
    lines.push(`    date: "${yamlEscape(item.date)}"`);
  }
  return lines.join('\n') + '\n';
}

async function main() {
  const [community, research] = await Promise.all([fetchHN(), fetchArxiv()]);
  const fs = await import('node:fs/promises');
  await fs.writeFile(OUT_PATH, toYaml(community, research));
  console.log(`Wrote ${community.length} community items, ${research.length} research items to _data/news.yml`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
