#!/usr/bin/env node
// Pulls narviai.com's News feed from two free, key-less, production-safe
// sources instead of a generic news aggregator: Hacker News (Algolia's
// public search API) for general tech — N.A.R.V.I.'s actual scope, same
// reasoning A.R.C.H.O.N. isn't AI-only either — and arXiv's public Atom
// feed for the AI-specific "Articles" section. Both explicitly permit
// this kind of use at this volume — no ToS risk the way NewsAPI's free
// "Developer" tier has (it forbids any non-localhost use, production
// included). Output is written verbatim: no summarizing, no
// paraphrasing, same discipline as PRISM's own News tab.
//
// Run: node scripts/fetch-news.js
// Writes: _data/news.yml

// No query filter — HN's own front page (by points, last few days) is
// "tech in general," which is the actual scope now. AI content shows up
// here naturally, same as it does on any real tech front page today; it
// isn't filtered down to only AI-tagged stories the way it was before.
const HN_MIN_POINTS = 40;
const HN_MAX_ITEMS = 10;

const ARXIV_CATEGORIES = ['cs.AI', 'cs.CL', 'cs.MA'];
const ARXIV_MAX_ITEMS = 6;

const OUT_PATH = new URL('../_data/news.yml', import.meta.url);

function yamlEscape(str) {
  return String(str).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

async function fetchHN() {
  const url = `https://hn.algolia.com/api/v1/search?tags=front_page&hitsPerPage=30&numericFilters=points%3E%3D${HN_MIN_POINTS}`;
  const res = await fetch(url);
  if (!res.ok) {
    console.error(`HN fetch failed: ${res.status}`);
    return [];
  }
  const data = await res.json();
  const items = (data.hits || [])
    .filter(hit => hit.url && hit.title)
    .map(hit => ({
      title: hit.title,
      url: hit.url,
      points: hit.points,
      comments: hit.num_comments,
      date: hit.created_at,
      discussion: `https://news.ycombinator.com/item?id=${hit.objectID}`,
    }));
  return items.sort((a, b) => b.points - a.points).slice(0, HN_MAX_ITEMS);
}

function parseArxivEntries(xml) {
  const entries = [];
  const blocks = xml.split('<entry>').slice(1);
  for (const block of blocks) {
    const title = (block.match(/<title>([\s\S]*?)<\/title>/) || [])[1];
    const link = (block.match(/<link href="([^"]+)" rel="alternate"/) || [])[1];
    const published = (block.match(/<published>([\s\S]*?)<\/published>/) || [])[1];
    const authorMatches = [...block.matchAll(/<name>([\s\S]*?)<\/name>/g)].map(m => m[1].trim());
    if (title && link) {
      entries.push({
        title: title.replace(/\s+/g, ' ').trim(),
        url: link,
        date: published,
        authors: authorMatches,
      });
    }
  }
  return entries;
}

async function fetchArxiv() {
  const category = ARXIV_CATEGORIES.map(c => `cat:${c}`).join('+OR+');
  const url = `https://export.arxiv.org/api/query?search_query=${category}&sortBy=submittedDate&sortOrder=descending&max_results=${ARXIV_MAX_ITEMS}`;
  const res = await fetch(url, { redirect: 'follow' });
  if (!res.ok) {
    console.error(`arXiv fetch failed: ${res.status}`);
    return [];
  }
  const xml = await res.text();
  return parseArxivEntries(xml);
}

function toYaml(tech, articles) {
  const lines = [];
  lines.push(`# Generated by scripts/fetch-news.js — do not hand-edit.`);
  lines.push(`generated_at: "${new Date().toISOString()}"`);
  lines.push(`tech:`);
  for (const item of tech) {
    lines.push(`  - title: "${yamlEscape(item.title)}"`);
    lines.push(`    url: "${yamlEscape(item.url)}"`);
    lines.push(`    discussion: "${yamlEscape(item.discussion)}"`);
    lines.push(`    points: ${item.points}`);
    lines.push(`    comments: ${item.comments}`);
    lines.push(`    date: "${yamlEscape(item.date)}"`);
  }
  lines.push(`articles:`);
  for (const item of articles) {
    lines.push(`  - title: "${yamlEscape(item.title)}"`);
    lines.push(`    url: "${yamlEscape(item.url)}"`);
    lines.push(`    authors: "${yamlEscape(item.authors.slice(0, 3).join(', ') + (item.authors.length > 3 ? ' et al.' : ''))}"`);
    lines.push(`    date: "${yamlEscape(item.date)}"`);
  }
  return lines.join('\n') + '\n';
}

async function main() {
  const [tech, articles] = await Promise.all([fetchHN(), fetchArxiv()]);
  const fs = await import('node:fs/promises');
  await fs.writeFile(OUT_PATH, toYaml(tech, articles));
  console.log(`Wrote ${tech.length} tech items, ${articles.length} articles to _data/news.yml`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
